//This list of currencies is from https://www.xe.com/symbols.php
export const CURRENCIES = {
  USD: { name: 'US Dollar', symbol: '$' },
  EUR: { name: 'Euro', symbol: '€' },
  GBP: { name: 'British Pound', symbol: '£' },
  JPY: { name: 'Japanese Yen', symbol: '¥' },
  AUD: { name: 'Australian Dollar', symbol: 'A$' },
  CAD: { name: 'Canadian Dollar', symbol: 'C$' },
  CHF: { name: 'Swiss Franc', symbol: 'Fr' },
  CNY: { name: 'Chinese Yuan', symbol: '¥' },
  INR: { name: 'Indian Rupee', symbol: '₹' },
  LKR: { name: 'Sri Lankan Rupee', symbol: 'Rs' },
  NZD: { name: 'New Zealand Dollar', symbol: 'NZ$' },
  SGD: { name: 'Singapore Dollar', symbol: 'S$' },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$' },
  AED: { name: 'UAE Dirham', symbol: 'د.إ' },
  SAR: { name: 'Saudi Riyal', symbol: '﷼' },
  KRW: { name: 'South Korean Won', symbol: '₩' },
  THB: { name: 'Thai Baht', symbol: '฿' },
  MYR: { name: 'Malaysian Ringgit', symbol: 'RM' },
  IDR: { name: 'Indonesian Rupiah', symbol: 'Rp' },
  PHP: { name: 'Philippine Peso', symbol: '₱' },
  PKR: { name: 'Pakistani Rupee', symbol: '₨' },
  BDT: { name: 'Bangladeshi Taka', symbol: '৳' },
  NPR: { name: 'Nepalese Rupee', symbol: 'रू' },
  MVR: { name: 'Maldivian Rufiyaa', symbol: 'Rf' },
  RUB: { name: 'Russian Ruble', symbol: '₽' },
  ZAR: { name: 'South African Rand', symbol: 'R' },
  BRL: { name: 'Brazilian Real', symbol: 'R$' },
  MXN: { name: 'Mexican Peso', symbol: 'Mex$' },
  ILS: { name: 'Israeli New Shekel', symbol: '₪' },
  QAR: { name: 'Qatari Riyal', symbol: 'ر.ق' },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  BHD: { name: 'Bahraini Dinar', symbol: '.د.ب' },
  OMR: { name: 'Omani Rial', symbol: 'ر.ع.' },
  EGP: { name: 'Egyptian Pound', symbol: 'E£' },
  PLN: { name: 'Polish Złoty', symbol: 'zł' },
  SEK: { name: 'Swedish Krona', symbol: 'kr' },
  DKK: { name: 'Danish Krone', symbol: 'kr' },
  NOK: { name: 'Norwegian Krone', symbol: 'kr' },
};

export const DEFAULT_FROM_CURRENCY = 'USD';
export const DEFAULT_TO_CURRENCY = 'EUR';